In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals


import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train.shape)

(60000, 28, 28)


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[-0.15018445, -0.1263996 , -0.18412349,  0.33114082, -0.4316433 ,
        -0.8698247 , -0.1004501 , -0.8223475 , -0.25854152, -0.38051176]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.10984541, 0.11248939, 0.10617992, 0.17775379, 0.08289836,
        0.05348675, 0.11544663, 0.05608739, 0.09856508, 0.08724731]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.9283214

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 5s 84us/sample - loss: 0.2964 - accuracy: 0.9139
Epoch 2/5
60000/60000 [==============================] - 5s 76us/sample - loss: 0.1448 - accuracy: 0.9569
Epoch 3/5
60000/60000 [==============================] - 5s 77us/sample - loss: 0.1079 - accuracy: 0.9681
Epoch 4/5
60000/60000 [==============================] - 5s 77us/sample - loss: 0.0888 - accuracy: 0.9727
Epoch 5/5
60000/60000 [==============================] - 5s 78us/sample - loss: 0.0758 - accuracy: 0.9761


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 1s - loss: 0.0795 - accuracy: 0.9770


[0.07953017164668999, 0.977]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.9825554e-09, 5.4780891e-09, 1.3214204e-06, 9.7736796e-05,
        2.0722660e-11, 1.6933470e-07, 1.6115112e-14, 9.9989986e-01,
        2.0821075e-07, 7.1731972e-07],
       [1.2871508e-06, 9.6759421e-04, 9.9900901e-01, 1.6554768e-05,
        1.4035001e-10, 1.9176277e-06, 6.7275727e-07, 1.0511159e-12,
        2.8240363e-06, 3.1163131e-11],
       [1.9459571e-06, 9.9830854e-01, 1.1275566e-04, 1.4635364e-05,
        7.8553567e-05, 7.5570692e-06, 9.6154086e-05, 1.0990310e-03,
        2.7439493e-04, 6.5841932e-06],
       [9.9988008e-01, 2.8078105e-06, 4.8664565e-06, 9.8521255e-08,
        4.1276564e-07, 2.6163336e-06, 7.8946068e-05, 2.7657232e-05,
        4.6395634e-08, 2.3463265e-06],
       [1.1285742e-05, 3.8123096e-09, 4.0985610e-06, 2.4552020e-07,
        9.9832124e-01, 7.0826438e-08, 3.2393316e-05, 8.8282140e-06,
        3.7719456e-06, 1.6180802e-03]], dtype=float32)>